cm = get_cm(); events = get_events(); gpm = _G.gpm;

local blacklist = gpm:blacklist()
local loader = gpm:loader()


--[[-VALID LOADER FUNCTIONS
DESCRIPTION: 
[
    Since we don't really know when the objects for these factions are going to exist, we instead add a set of traits to the "loader" which are given
    automatically to each faction when their geopolitical object is created.
]
loader:add_default_preference_for_faction("faction_key", "property_key", #preference_value#)
loader:add_default_preference_for_subculture("sc_key", "property_key", #preference_value#)
loader:add_region_to_group("region_key", "group_key")
loader:add_default_property_for_subculture("sc_key", "property_key")
loader:add_default_property_for_faction("faction_key", "property_key")
loader:add_default_property_for_region("region_key", "property_key")
loader:add_default_property_for_region_group("group_key", "property_key")
loader:add_default_preference_for_faction("faction_key", "property_key", #preference_value#)
loader:add_default_preference_for_subculture("sc_key", "property_key", #preference_value#)
--]]
--[[-VALID BLACKLIST FUNCTIONS
DESCRIPTION: 
[
    Since factions inherit traits through the regions they own, it is often undesirable for a faction to get a trait from a region, because it doesn't fit them.
    For example, we wouldn't want Dwarf lords getting a penalty with other dwarfs for owning a Karak, but we would want other factions to get that penalty.
    Dynamically adding and removing traits from the region would be hard, so instead we have a blacklist which can prevent certain factions or subcultures from
    inhereting the traits which don't fit them. 
]
blacklist:set_faction_blacklisted_for_property("property_key", "faction_key")
blacklist:set_subculture_blacklisted_for_property("property_key", "sc_key")
--]]

--# type global GEOPOLITIC_GROUP_NAME = 
--# "empire_northern" | "empire_southern" | "sylvania" | "marienburg" |
--# "grey_mountains" | "black_mountains" |
--# "karaz_ankor_central" | "karaz_ankor_southern" | "karaz_ankor_northern" | "badlands" | 
--# "worlds_edge_mountains" |
--# "nehekhara" | "araby" | "devils_backbone" |
--# "bretonnia" | "athel_loren" | "estalia" | "tilea" | "kislev" | "sartosa" | "border_princes" |
--# "norsca" | "wastes" | "kraka_drak" |
--# "ulthuan_inner" | "ulthuan_outer" | "ulthuan_gate" | "elf_colonies" |
--# "temple_city" | "jungle" | "new_world_colony" |
--# "naggaroth_cities" | "nagaroth_mountain" | "nagaroth_wilds" |
--# "nagash" 

--REGION GROUPINGS
local regions_to_groups = {
    ["wh_main_nordland_dietershafen"] = "empire_northern",
    ["wh_main_nordland_salzenmund"] = "empire_northern",
    ["wh_main_ostland_norden"] = "empire_northern",
    ["wh_main_ostland_wolfenburg"] = "empire_northern",
    ["wh_main_ostland_castle_von_rauken"] = "empire_northern",
    ["wh_main_hochland_brass_keep"] = "empire_northern",
    ["wh_main_hochland_hergig"] = "empire_northern",
    ["wh_main_middenland_carroburg"] = "empire_northern",
    ["wh_main_middenland_weismund"] = "empire_northern",
    ["wh_main_middenland_middenheim"] = "empire_northern",
    ["wh_main_talabecland_kemperbad"] = "empire_southern",
    ["wh_main_talabecland_talabheim"] = "empire_southern",
    ["wh_main_ostermark_bechafen"] = "empire_southern",
    ["wh_main_ostermark_essen"] = "empire_southern",
    ["wh_main_reikland_eilhart"] = "empire_southern",
    ["wh_main_reikland_altdorf"] = "empire_southern",
    ["wh_main_reikland_helmgart"] = "empire_southern",
    ["wh_main_reikland_grunburg"] = "empire_southern",
    ["wh_main_stirland_wurtbad"] = "empire_southern",
    ["wh_main_stirland_the_moot"] = "empire_southern",
    ["wh_main_averland_averheim"] = "empire_southern",
    ["wh_main_averland_grenzstadt"] = "empire_southern",
    ["wh_main_wissenland_nuln"] = "empire_southern",
    ["wh_main_wissenland_wissenburg"] = "empire_southern",
    ["wh_main_wissenland_pfeildorf"] = "empire_southern",
    ["wh_main_western_sylvania_fort_oberstyre"] = "sylvania",
    ["wh_main_western_sylvania_castle_templehof"] = "sylvania",
    ["wh_main_western_sylvania_schwartzhafen"] = "sylvania",
    ["wh_main_eastern_sylvania_eschen"] = "sylvania",
    ["wh_main_eastern_sylvania_waldenhof"] = "sylvania",
    ["wh_main_eastern_sylvania_castle_drakenhof"] = "sylvania",
    ["wh_main_northern_grey_mountains_grung_zint"] = "grey_mountains",
    ["wh_main_northern_grey_mountains_blackstone_post"] = "grey_mountains",
    ["wh_main_northern_grey_mountains_karak_ziflin"] = "grey_mountains",
    ["wh_main_southern_grey_mountains_karak_azgaraz"] = "grey_mountains",
    ["wh_main_southern_grey_mountains_karak_norn"] = "grey_mountains",
    ["wh_main_southern_grey_mountains_grimhold"] = "grey_mountains",
    ["wh_main_the_vaults_karak_bhufdar"] = "black_mountains",
    ["wh_main_the_vaults_karak_izor"] = "black_mountains",
    ["wh_main_the_vaults_zarakzil"] = "black_mountains",
    ["wh_main_black_mountains_karak_hirn"] = "black_mountains",
    ["wh_main_black_mountains_karak_angazhar"] = "black_mountains",
    ["wh_main_black_mountains_mighdal_vongalbarak"] = "black_mountains",
    ["wh_main_zhufbar_karag_dromar"] = "karaz_ankor_central",
    ["wh_main_zhufbar_oakenhammer"] = "karaz_ankor_central",
    ["wh_main_zhufbar_zhufbar"] = "karaz_ankor_central",
    ["wh_main_the_silver_road_karaz_a_karak"] = "karaz_ankor_central",
    ["wh_main_the_silver_road_the_pillars_of_grungni"] = "karaz_ankor_central",
    ["wh_main_northern_worlds_edge_mountains_karak_ungor"] = "karaz_ankor_northern",
    ["wh_main_northern_worlds_edge_mountains_khazid_irkulaz"] = "karaz_ankor_northern",
    ["wh_main_peak_pass_karak_kadrin"] = "karaz_ankor_northern",
    ["wh_main_peak_pass_gnashraks_lair"] = "worlds_edge_mountains",
    ["wh_main_rib_peaks_grom_peak"] = "worlds_edge_mountains",
    ["wh_main_rib_peaks_mount_gunbad"] = "karaz_ankor_central",
    ["wh_main_blood_river_valley_barak_varr"] = "karaz_ankor_central",
    ["wh_main_blood_river_valley_varenka_hills"] = "karaz_ankor_central",
    ["wh_main_blood_river_valley_dok_karaz"] = "karaz_ankor_central",
    ["wh_main_blood_river_valley_barag_dawazbag"] = "karaz_ankor_central",
    ["wh_main_the_silver_road_mount_squighorn"] = "worlds_edge_mountains",
    ["wh_main_death_pass_karag_dron"] = "karaz_ankor_southern",
    ["wh_main_death_pass_iron_rock"] = "karaz_ankor_southern",
    ["wh_main_death_pass_karak_drazh"] = "karaz_ankor_southern",
    ["wh_main_southern_badlands_gronti_mingol"] = "badlands",
    ["wh_main_western_badlands_ekrund"] = "badlands",
    ["wh_main_western_badlands_stonemine_tower"] = "badlands",
    ["wh_main_western_badlands_bitterstone_mine"] = "badlands",
    ["wh_main_western_badlands_dragonhorn_mines"] = "badlands",
    ["wh_main_eastern_badlands_valayas_sorrow"] = "badlands",
    ["wh_main_eastern_badlands_karak_eight_peaks"] = "karaz_ankor_southern",
    ["wh_main_eastern_badlands_crooked_fang_fort"] = "worlds_edge_mountains",
    ["wh_main_eastern_badlands_dringorackaz"] = "karaz_ankor_southern",
    ["wh_main_blightwater_karak_azgal"] = "karaz_ankor_southern",
    ["wh_main_blightwater_kradtommen"] = "worlds_edge_mountains",
    ["wh_main_blightwater_misty_mountain"] = "worlds_edge_mountains",
    ["wh_main_couronne_et_languille_languille"] = "bretonnia",
    ["wh_main_couronne_et_languille_couronne"] = "bretonnia",
    ["wh_main_lyonesse_lyonesse"] = "bretonnia",
    ["wh_main_lyonesse_mousillon"] = "bretonnia",
    ["wh_main_forest_of_arden_castle_artois"] = "bretonnia",
    ["wh_main_forest_of_arden_gisoreux"] = "bretonnia",
    ["wh_main_bordeleaux_et_aquitaine_bordeleaux"] = "bretonnia",
    ["wh_main_bordeleaux_et_aquitaine_aquitaine"] = "bretonnia",
    ["wh_main_bastonne_et_montfort_castle_bastonne"] = "bretonnia",
    ["wh_main_bastonne_et_montfort_montfort"] = "bretonnia",
    ["wh_main_carcassone_et_brionne_brionne"] = "bretonnia",
    ["wh_main_carcassone_et_brionne_castle_carcassonne"] = "bretonnia",
    ["wh_main_parravon_et_quenelles_quenelles"] = "bretonnia",
    ["wh_main_parravon_et_quenelles_parravon"] = "bretonnia",
    ["wh_main_estalia_bilbali"] = "estalia",
    ["wh_main_estalia_magritta"] = "estalia",
    ["wh_main_estalia_tobaro"] = "estalia",
    ["wh_main_tilea_miragliano"] = "tilea",
    ["wh_main_tilea_luccini"] = "tilea",
    ["wh2_main_sartosa_sartosa"] = "sartosa",
    ["wh_main_western_border_princes_myrmidens"] = "border_princes",
    ["wh_main_western_border_princes_zvorak"] = "border_princes",
    ["wh_main_eastern_border_princes_matorca"] = "border_princes",
    ["wh_main_eastern_border_princes_akendorf"] = "border_princes",
    ["wh_main_troll_country_zoishenk"] = "kislev",
    ["wh_main_troll_country_erengrad"] = "kislev",
    ["wh_main_northern_oblast_fort_straghov"] = "kislev",
    ["wh_main_northern_oblast_fort_ostrosk"] = "kislev",
    ["wh_main_eastern_oblast_praag"] = "kislev",
    ["wh_main_eastern_oblast_volksgrad"] = "kislev",
    ["wh_main_southern_oblast_zavastra"] = "kislev",
    ["wh_main_southern_oblast_kislev"] = "kislev",
    ["wh_main_southern_oblast_fort_jakova"] = "kislev",
    ["wh_main_helspire_mountains_serpent_jetty"] = "norsca",
    ["wh_main_helspire_mountains_the_monolith_of_katam"] = "norsca",
    ["wh_main_helspire_mountains_graeling_moot"] = "norsca",
    ["wh_main_vanaheim_mountains_troll_fjord"] = "norsca",
    ["wh_main_vanaheim_mountains_bjornlings_gathering"] = "norsca",
    ["wh_main_vanaheim_mountains_pack_ice_bay"] = "norsca",
    ["wh_main_mountains_of_naglfari_varg_camp"] = "norsca",
    ["wh_main_mountains_of_naglfari_naglfari_plain"] = "norsca",
    ["wh_main_ice_tooth_mountains_doomkeep"] = "norsca",
    ["wh_main_ice_tooth_mountains_icedrake_fjord"] = "norsca",
    ["wh_main_ice_tooth_mountains_longship_graveyard"] = "norsca",
    ["wh_main_mountains_of_hel_altar_of_spawns"] = "norsca",
    ["wh_main_mountains_of_hel_aeslings_conclave"] = "norsca",
    ["wh_main_mountains_of_hel_winter_pyre"] = "norsca",
    ["wh_main_trollheim_mountains_sarl_encampment"] = "norsca",
    ["wh_main_trollheim_mountains_bay_of_blades"] = "norsca",
    ["wh_main_trollheim_mountains_the_tower_of_khrakk"] = "norsca",
    ["wh_main_gianthome_mountains_kraka_drak"] = "kraka_drak",
    ["wh_main_gianthome_mountains_khazid_bordkarag"] = "kraka_drak",
    ["wh_main_gianthome_mountains_sjoktraken"] = "kraka_drak",
    ["wh_main_goromandy_mountains_frozen_landing"] = "norsca",
    ["wh_main_goromandy_mountains_baersonlings_camp"] = "norsca",
    ["wh_main_the_wasteland_gorssel"] = "marienburg",
    ["wh_main_the_wasteland_marienburg"] = "marienburg",
    ["wh_main_blightwater_deff_gorge"] = "worlds_edge_mountains",
    ["wh_main_desolation_of_nagash_black_iron_mine"] = "worlds_edge_mountains",
    ["wh_main_desolation_of_nagash_karak_azul"] = "karaz_ankor_southern",
    ["wh_main_desolation_of_nagash_spitepeak"] = "worlds_edge_mountains",
    ["wh_main_southern_badlands_agrul_migdhal"] = "badlands",
    ["wh_main_southern_badlands_galbaraz"] = "badlands",
    ["wh_main_southern_badlands_gor_gazan"] = "badlands",
    ["wh_main_yn_edri_eternos_the_oak_of_ages"] = "athel_loren",
    ["wh_main_athel_loren_vauls_anvil"] = "athel_loren",
    ["wh_main_athel_loren_waterfall_palace"] = "athel_loren",
    ["wh_main_athel_loren_yn_edryl_korian"] = "athel_loren",
    ["wh_main_athel_loren_crag_halls"] = "athel_loren",
    ["wh2_main_aghol_wastelands_fortress_of_the_damned"] = "wastes",
    ["wh2_main_aghol_wastelands_palace_of_princes"] = "wastes",
    ["wh2_main_aghol_wastelands_the_palace_of_ruin"] = "wastes",
    ["wh2_main_ash_river_numas"] = "nehekhara",
    ["wh2_main_ash_river_quatar"] = "nehekhara",
    ["wh2_main_ash_river_springs_of_eternal_life"] = "nehekhara",
    ["wh2_main_avelorn_evershale"] = "ulthuan_inner",
    ["wh2_main_avelorn_gaean_vale"] = "ulthuan_inner",
    ["wh2_main_avelorn_tor_saroir"] = "ulthuan_inner",
    ["wh2_main_blackspine_mountains_plain_of_dogs"] = "worlds_edge_mountains",
    ["wh2_main_blackspine_mountains_plain_of_spiders"] = "worlds_edge_mountains",
    ["wh2_main_blackspine_mountains_red_desert"] = "worlds_edge_mountains",
    ["wh2_main_caledor_vauls_anvil"] = "ulthuan_outer",
    ["wh2_main_caledor_tor_sethai"] = "ulthuan_outer",
    ["wh2_main_chrace_elisia"] = "ulthuan_outer",
    ["wh2_main_chrace_tor_achare"] = "ulthuan_outer",
    ["wh2_main_coast_of_araby_al_haikk"] = "araby",
    ["wh2_main_coast_of_araby_copher"] = "araby",
    ["wh2_main_atalan_mountains_martek"] = "araby",
    ["wh2_main_cothique_mistnar"] = "ulthuan_outer",
    ["wh2_main_cothique_tor_koruali"] = "ulthuan_outer",
    ["wh2_main_deadwood_dargoth"] = "nagaroth_wilds",
    ["wh2_main_deadwood_nagrar"] = "nagaroth_wilds",
    ["wh2_main_deadwood_shagrath"] = "nagaroth_wilds",
    ["wh2_main_deadwood_the_frozen_city"] = "nagaroth_wilds",
    ["wh2_main_doom_glades_hag_hall"] = "naggaroth_cities",
    ["wh2_main_doom_glades_ice_rock_gorge"] = "nagaroth_wilds",
    ["wh2_main_doom_glades_temple_of_addaioth"] = "nagaroth_wilds",
    ["wh2_main_doom_glades_vauls_anvil"] = "naggaroth_cities",
    ["wh2_main_eataine_angerrial"] = "ulthuan_outer",
    ["wh2_main_eataine_lothern"] = "ulthuan_outer",
    ["wh2_main_eataine_shrine_of_asuryan"] = "ulthuan_outer",
    ["wh2_main_eataine_tower_of_lysean"] = "ulthuan_outer",
    ["wh2_main_griffon_gate"] = "ulthuan_gate",
    ["wh2_main_ellyrion_tor_elyr"] = "ulthuan_inner",
    ["wh2_main_ellyrion_whitefire_tor"] = "ulthuan_inner",
    ["wh2_main_great_desert_of_araby_bel_aliad"] = "araby",
    ["wh2_main_great_desert_of_araby_black_tower_of_arkhan"] = "araby",
    ["wh2_main_great_desert_of_araby_pools_of_despair"] = "araby",
    ["wh2_main_headhunters_jungle_mangrove_coast"] = "jungle",
    ["wh2_main_headhunters_jungle_marks_of_the_old_ones"] = "jungle",
    ["wh2_main_huahuan_desert_chamber_of_visions"] = "temple_city",
    ["wh2_main_huahuan_desert_sentinels_of_xeti"] = "jungle",
    ["wh2_main_huahuan_desert_the_golden_colossus"] = "jungle",
    ["wh2_main_iron_mountains_altar_of_ultimate_darkness"] = "nagaroth_mountain",
    ["wh2_main_iron_mountains_har_kaldra"] = "nagaroth_mountain",
    ["wh2_main_iron_mountains_naggarond"] = "naggaroth_cities",
    ["wh2_main_iron_mountains_rackdo_gorge"] = "nagaroth_mountain",
    ["wh2_main_ironfrost_glacier_dagraks_end"] = "wastes",
    ["wh2_main_ironfrost_glacier_ironfrost"] = "wastes",
    ["wh2_main_isthmus_of_lustria_fallen_gates"] = "temple_city",
    ["wh2_main_isthmus_of_lustria_hexoatl"] = "temple_city",
    ["wh2_main_isthmus_of_lustria_skeggi"] = "new_world_colony",
    ["wh2_main_isthmus_of_lustria_ziggurat_of_dawn"] = "temple_city",
    ["wh2_main_jungles_of_green_mists_spektazuma"] = "jungle",
    ["wh2_main_jungles_of_green_mists_wellsprings_of_eternity"] = "jungle",
    ["wh2_main_atalan_mountains_eye_of_the_panther"] = "araby",
    ["wh2_main_land_of_assassins_lashiek"] = "araby",
    ["wh2_main_land_of_assassins_palace_of_the_wizard_caliph"] = "araby",
    ["wh2_main_land_of_assassins_sorcerers_islands"] = "araby",
    ["wh2_main_land_of_the_dead_khemri"] = "nehekhara",
    ["wh2_main_great_mortis_delta_black_pyramid_of_nagash"] = "nagash",
    ["wh2_main_land_of_the_dead_zandri"] = "nehekhara",
    ["wh2_main_great_desert_of_araby_el-kalabad"] = "nehekhara",
    ["wh2_main_atalan_mountains_vulture_mountain"] = "araby",
    ["wh2_main_phoenix_gate"] = "ulthuan_gate",
    ["wh2_main_nagarythe_shrine_of_khaine"] = "ulthuan_outer",
    ["wh2_main_nagarythe_tor_anlec"] = "ulthuan_outer",
    ["wh2_main_nagarythe_tor_dranil"] = "ulthuan_outer",
    ["wh2_main_northern_great_jungle_chaqua"] = "temple_city",
    ["wh2_main_northern_great_jungle_temple_of_tlencan"] = "jungle",
    ["wh2_main_northern_great_jungle_xahutec"] = "temple_city",
    ["wh2_main_northern_great_jungle_xlanhuapec"] = "temple_city",
    ["wh2_main_northern_jungle_of_pahualaxa_macu_peaks"] = "jungle",
    ["wh2_main_northern_jungle_of_pahualaxa_port_reaver"] = "new_world_colony",
    ["wh2_main_northern_jungle_of_pahualaxa_shrine_of_sotek"] = "jungle",
    ["wh2_main_northern_jungle_of_pahualaxa_swamp_town"] = "new_world_colony",
    ["wh2_main_obsidian_peaks_circle_of_destruction"] = "nagaroth_wilds",
    ["wh2_main_obsidian_peaks_clar_karond"] = "naggaroth_cities",
    ["wh2_main_obsidian_peaks_storag_kor"] = "nagaroth_wilds",
    ["wh2_main_obsidian_peaks_venom_glade"] = "nagaroth_wilds",
    ["wh2_main_saphery_port_elistor"] = "ulthuan_inner",
    ["wh2_main_saphery_tor_finu"] = "ulthuan_inner",
    ["wh2_main_saphery_tower_of_hoeth"] = "ulthuan_inner",
    ["wh2_main_shifting_sands_antoch"] = "group_name",
    ["wh2_main_shifting_sands_bhagar"] = "group_name",
    ["wh2_main_shifting_sands_ka-sabar"] = "group_name",
    ["wh2_main_southern_great_jungle_axlotl"] = "group_name",
    ["wh2_main_southern_great_jungle_itza"] = "temple_city",
    ["wh2_main_headhunters_jungle_oyxl"] = "group_name",
    ["wh2_main_southern_great_jungle_subatuun"] = "group_name",
    ["wh2_main_southern_jungle_of_pahualaxa_floating_pyramid"] = "group_name",
    ["wh2_main_southern_jungle_of_pahualaxa_monument_of_the_moon"] = "group_name",
    ["wh2_main_southern_jungle_of_pahualaxa_pahuax"] = "temple_city",
    ["wh2_main_southern_jungle_of_pahualaxa_the_high_sentinel"] = "group_name",
    ["wh2_main_southlands_worlds_edge_mountains_karak_zorn"] = "group_name",
    ["wh2_main_southlands_worlds_edge_mountains_lost_plateau"] = "group_name",
    ["wh2_main_southlands_worlds_edge_mountains_mount_arachnos"] = "group_name",
    ["wh2_main_spine_of_sotek_hualotal"] = "group_name",
    ["wh2_main_spine_of_sotek_mine_of_the_bearded_skulls"] = "group_name",
    ["wh2_main_spine_of_sotek_monument_of_izzatal"] = "group_name",
    ["wh2_main_titan_peaks_ancient_city_of_quintex"] = "group_name",
    ["wh2_main_the_black_coast_arnheim"] = "group_name",
    ["wh2_main_the_black_coast_bleak_hold_fortress"] = "group_name",
    ["wh2_main_the_black_flood_cragroth_deep"] = "group_name",
    ["wh2_main_the_black_flood_hag_graef"] = "naggaroth_cities",
    ["wh2_main_the_black_flood_shroktak_mount"] = "group_name",
    ["wh2_main_the_black_flood_temple_of_khaine"] = "group_name",
    ["wh2_main_the_broken_land_blacklight_tower"] = "group_name",
    ["wh2_main_the_broken_land_karond_kar"] = "naggaroth_cities",
    ["wh2_main_the_broken_land_slavers_point"] = "group_name",
    ["wh2_main_the_chill_road_ashrak"] = "group_name",
    ["wh2_main_the_chill_road_ghrond"] = "naggaroth_cities",
    ["wh2_main_the_chill_road_the_great_arena"] = "group_name",
    ["wh2_main_the_clawed_coast_hoteks_column"] = "group_name",
    ["wh2_main_the_clawed_coast_the_monoliths"] = "group_name",
    ["wh2_main_the_clawed_coast_the_twisted_glade"] = "group_name",
    ["wh2_main_the_creeping_jungle_temple_of_kara"] = "group_name",
    ["wh2_main_the_creeping_jungle_tlanxla"] = "group_name",
    ["wh2_main_the_creeping_jungle_tlaxtlan"] = "temple_city",
    ["wh2_main_the_road_of_skulls_har_ganeth"] = "naggaroth_cities",
    ["wh2_main_the_road_of_skulls_kauark"] = "group_name",
    ["wh2_main_the_road_of_skulls_spite_reach"] = "group_name",
    ["wh2_main_the_road_of_skulls_the_black_pillar"] = "group_name",
    ["wh2_main_eagle_gate"] = "ulthuan_gate",
    ["wh2_main_tiranoc_tor_anroc"] = "group_name",
    ["wh2_main_tiranoc_whitepeak"] = "group_name",
    ["wh2_main_titan_peaks_ironspike"] = "group_name",
    ["wh2_main_titan_peaks_ssildra_tor"] = "group_name",
    ["wh2_main_titan_peaks_the_moon_shard"] = "group_name",
    ["wh2_main_vampire_coast_the_blood_swamps"] = "new_world_colony",
    ["wh2_main_vampire_coast_pox_marsh"] = "new_world_colony",
    ["wh2_main_vampire_coast_the_awakening"] = "new_world_colony",
    ["wh2_main_volcanic_islands_the_star_tower"] = "elf_colony",
    ["wh2_main_yvresse_elessaeli"] = "group_name",
    ["wh2_main_yvresse_tor_yvresse"] = "group_name",
    ["wh2_main_skavenblight_skavenblight"] = "wastes",
    ["wh2_main_hell_pit_hell_pit"] = "wastes",
    ["wh2_main_unicorn_gate"] = "ulthuan_gate",
    ["wh2_main_coast_of_araby_fyrus"] = "group_name",
    ["wh2_main_charnel_valley_karag_orrud"] = "group_name",
    ["wh2_main_charnel_valley_granite_massif"] = "group_name",
    ["wh2_main_devils_backbone_lahmia"] = "group_name",
    ["wh2_main_devils_backbone_mahrak"] = "group_name",
    ["wh2_main_devils_backbone_lybaras"] = "group_name",
    ["wh2_main_crater_of_the_walking_dead_doom_glade"] = "group_name",
    ["wh2_main_crater_of_the_walking_dead_rasetra"] = "group_name",
    ["wh2_main_southlands_jungle_teotiqua"] = "group_name",
    ["wh2_main_southlands_jungle_golden_tower_of_the_gods"] = "group_name",
    ["wh2_main_kingdom_of_beasts_temple_of_skulls"] = "group_name",
    ["wh2_main_kingdom_of_beasts_serpent_coast"] = "group_name",
    ["wh2_main_kingdom_of_beasts_the_cursed_jungle"] = "group_name",
    ["wh2_main_volcanic_islands_fuming_serpent"] = "group_name"
} --:map<string, GEOPOLITIC_GROUP_NAME>