pm = _G.pm
local TAX_RATE_EFFECT_JUNCTIONS = {
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_def_dark_elves_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_hef_high_elves_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_lzd_lizardmen_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh2_main_sc_skv_skaven_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_brt_bretonnia_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_dwf_dwarfs_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_emp_empire_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_ksl_kislev_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_1", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_1", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_1", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_1", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_1", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_2", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_2", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -2, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_2", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = -10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_2", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = -15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_2", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = 1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_3", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_3", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -4, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_3", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 0, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_3", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 5, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_3", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -1, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_4", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -12, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_4", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -6, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_4", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 10, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_4", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 15, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_4", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -3, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_5", ["effect_key"] = "wec_game_growth", ["effect_scope"] = "region_to_province_own", ["value"] = -24, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_5", ["effect_key"] = "wec_game_public_order", ["effect_scope"] = "region_to_province_own", ["value"] = -8, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_5", ["effect_key"] = "wec_game_town_income", ["effect_scope"] = "region_to_province_own", ["value"] = 20, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_5", ["effect_key"] = "wec_script_vars_unit_pool_mod", ["effect_scope"] = "region_to_province_own", ["value"] = 25, ["advancement_stage"] = "start_turn_completed" },
    { ["effect_bundle_key"] = "wec_tax_wh_main_sc_teb_teb_5", ["effect_key"] = "wec_script_vars_wealth", ["effect_scope"] = "region_to_province_own", ["value"] = -5, ["advancement_stage"] = "start_turn_completed" }
}--:vector<{effect_bundle_key: string, effect_key: string, effect_scope:string, value:number, advancement_stage: string}>

details = {} --:map<string, map<string, WHATEVER>>

for i = 1, #TAX_RATE_EFFECT_JUNCTIONS do
    local instance = TAX_RATE_EFFECT_JUNCTIONS[i]
    local key = instance.effect_bundle_key
    if details[key] == nil then
        details[key] = {}
        detail = details[key]
        detail._level = string.sub(key, -1)
        detail._UIName = effect.get_localised_string("effect_bundles_localised_title_"..key)
        detail._UIEffects = {}
        detail._bundle = key
    end
    local detail = details[key]
    local db_effect = instance.effect_key
    local value = instance.value
    local col = "red"
    if value > 0 then
        col = "green"
    end
    local loc = effect.get_localised_string("effects_description_"..db_effect)
    local effect_text = "[[col:"..col.."]]".. string.gsub(loc, "%+n", tostring(value))..[[/col]]
    table.insert(detail._UIEffects, effect_text) 
    if string.find(db_effect, "script_var") then
        if string.find(db_effect, "wealth") then
            detail._wealthEffects = value
        end
        if string.find(db_effect, "unit_pool_mod") then
            detail._unitProdEffects = 1 + value/100
        end
    end
end

for key, detail in pairs(details) do
    --# assume detail: TAX_DETAIL
    local sc = string.sub(string.gsub(key, "wec_tax_", ""), 1, -3)
    pm:add_tax_level_for_subculture(sc, detail._level, detail)
end